export default [
  {
    img: "./images/Boston-terrier500x500.jpg",
    petname: "rocky",
    uid: "20730392",
    category: "Rocky",
    breed: "Boston Terrier",
    color: "Black",
    gender: "Male",
    vaccinated: "yes",
    age: "2y",
    address: "House No. 465 Street No.6",
    pickup: "At : 11:00 From : 05-04-2023 To : 10-04-2023",
    details: "Shiro has sharp teeth so that it can eat flesh very easily, barks loudly and attacks the strangers",
  },
  {
    img: "./images/Beagle500x500.jpg",
    petname: "rocky",
    uid: "20730392",
    category: "Rocky",
    breed: "Boston Terrier",
    color: "Black",
    gender: "Male",
    vaccinated: "yes",
    age: "2y",
    address: "House No. 465 Street No.6",
    pickup: "At : 11:00 From : 05-04-2023 To : 10-04-2023",
    details: "Shiro has sharp teeth so that it can eat flesh very easily, barks loudly and attacks the strangers",
  },
  {
    img: "./images/BritishShorthair500x500.jpg",
    petname: "rocky",
    uid: "20730392",
    category: "Rocky",
    breed: "Boston Terrier",
    color: "Black",
    gender: "Male",
    vaccinated: "yes",
    age: "2y",
    address: "House No. 465 Street No.6",
    pickup: "At : 11:00 From : 05-04-2023 To : 10-04-2023",
    details: "Shiro has sharp teeth so that it can eat flesh very easily, barks loudly and attacks the strangers",
  },
  {
    img: "./images/german500x500.jpg",
    petname: "rocky",
    uid: "20730392",
    category: "Rocky",
    breed: "Boston Terrier",
    color: "Black",
    gender: "Male",
    vaccinated: "yes",
    age: "2y",
    address: "House No. 465 Street No.6",
    pickup: "At : 11:00 From : 05-04-2023 To : 10-04-2023",
    details: "Shiro has sharp teeth so that it can eat flesh very easily, barks loudly and attacks the strangers",
  },
  {
    img: "./images/Siamesecat500x500.jpg",
    petname: "rocky",
    uid: "20730392",
    category: "Rocky",
    breed: "Boston Terrier",
    color: "Black",
    gender: "Male",
    vaccinated: "yes",
    age: "2y",
    address: "House No. 465 Street No.6",
    pickup: "At : 11:00 From : 05-04-2023 To : 10-04-2023",
    details: "Shiro has sharp teeth so that it can eat flesh very easily, barks loudly and attacks the strangers",
  },
  {
    img: "./images/Sphynxcat500x500.jpg",
    petname: "rocky",
    uid: "20730392",
    category: "Rocky",
    breed: "Boston Terrier",
    color: "Black",
    gender: "Male",
    vaccinated: "yes",
    age: "2y",
    address: "House No. 465 Street No.6",
    pickup: "At : 11:00 From : 05-04-2023 To : 10-04-2023",
    details: "Shiro has sharp teeth so that it can eat flesh very easily, barks loudly and attacks the strangers",
  },
  {
    img: "./images/500-2.jpg",
    petname: "rocky",
    uid: "20730392",
    category: "Rocky",
    breed: "Boston Terrier",
    color: "Black",
    gender: "Male",
    vaccinated: "yes",
    age: "2y",
    address: "House No. 465 Street No.6",
    pickup: "At : 11:00 From : 05-04-2023 To : 10-04-2023",
    details: "Shiro has sharp teeth so that it can eat flesh very easily, barks loudly and attacks the strangers",
  },
];
